// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include "ui.h"
#include "esp_sntp.h"
#include "esp_log.h"
#include "esp_http_client.h"
#include "cJSON.h"
#include "esp_tls.h"
#include "esp_crt_bundle.h"
#include "webscoket.h"
#include "count.h"
static const char *TAG = "ui_screen";

extern lv_obj_t *ui_feedplantext;
extern lv_obj_t *ui_times;
extern lv_obj_t *ui_status;
extern lv_obj_t *ui_data;
extern lv_obj_t *ui_timehs;

#define DEVICE_UUID "123e4567-e89b-12d3-a456-426614174000"
#define SERVER_URL "https://thinkfuture.top/api/infor/get"
extern const uint8_t server_thinkfuture_pem_start[] asm("_binary_thinkfuture_pem_start");
extern const uint8_t server_thinkfuture_pem_end[] asm("_binary_thinkfuture_pem_end");
static char *http_response_buf = NULL;
static int http_response_len = 0;

static void update_rtc_time_cb(lv_timer_t *timer)
{
    time_t now;
    struct tm timeinfo;
    time(&now);
    localtime_r(&now, &timeinfo);

    static char time_str[16];
    static char date_str[16];
    strftime(time_str, sizeof(time_str), "%H:%M:%S", &timeinfo);
    strftime(date_str, sizeof(date_str), "%Y/%m/%d", &timeinfo);

    lv_label_set_text(ui_timehs, time_str);
    lv_label_set_text(ui_data, date_str);
}

esp_err_t _http_event_handler(esp_http_client_event_t *evt)
{
    switch (evt->event_id)
    {
    case HTTP_EVENT_ERROR:
        ESP_LOGW(TAG, "HTTP_EVENT_ERROR");
        break;
    case HTTP_EVENT_ON_CONNECTED:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_CONNECTED");
        break;
    case HTTP_EVENT_HEADERS_SENT:
        ESP_LOGI(TAG, "HTTP_EVENT_HEADER(S)_SENT");
        break;
    case HTTP_EVENT_ON_HEADER:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_HEADER: %s: %s", evt->header_key, evt->header_value);
        break;
    case HTTP_EVENT_ON_DATA:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
        if (!esp_http_client_is_chunked_response(evt->client))
        {
            http_response_buf = realloc(http_response_buf, http_response_len + evt->data_len + 1);
            if (http_response_buf == NULL)
            {
                ESP_LOGE(TAG, "Failed to allocate memory for response");
                return ESP_FAIL;
            }
            memcpy(http_response_buf + http_response_len, evt->data, evt->data_len);
            http_response_len += evt->data_len;
            http_response_buf[http_response_len] = 0; // Null terminate
        }
        break;
    case HTTP_EVENT_ON_FINISH:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_FINISH");

        if (http_response_buf != NULL)
        {
            ESP_LOGI(TAG, "Received JSON (%d bytes):\n%s", http_response_len, http_response_buf);

            cJSON *root = cJSON_Parse(http_response_buf);
            if (root)
            {
                cJSON *feed1 = cJSON_GetObjectItem(root, "feed_task_time1");
                cJSON *feed2 = cJSON_GetObjectItem(root, "feed_task_time2");
                cJSON *feed3 = cJSON_GetObjectItem(root, "feed_task_time3");
                cJSON *feed_count = cJSON_GetObjectItem(root, "feed_count");
                // cJSON *status = cJSON_GetObjectItem(root, "status");
                cJSON *feed_task_status1 = cJSON_GetObjectItem(root, "feed_task_status1");
                cJSON *feed_task_status2 = cJSON_GetObjectItem(root, "feed_task_status2");
                cJSON *feed_task_status3 = cJSON_GetObjectItem(root, "feed_task_status3");
                if (feed1 && feed2 && feed3 && feed_count)
                {
                    char text[64];
                    snprintf(text, sizeof(text), "1-->%s\n2-->%s\n3-->%s",
                             feed1->valuestring, feed2->valuestring, feed3->valuestring);
                    lv_label_set_text(ui_feedplantext, text);
                    lv_obj_align(ui_feedplantext, LV_ALIGN_CENTER, -80, 61);

                    char timestr[16];
                    snprintf(timestr, sizeof(timestr), "%d times\n%d H", get_count(), temperature);
                    lv_label_set_text(ui_times, timestr);
                    lv_obj_align(ui_times, LV_ALIGN_CENTER, 100, 6);

                    char text_status[64];
                    snprintf(text_status, sizeof(text_status), "%d\n%d\n%d",
                             feed_task_status1->valueint, feed_task_status2->valueint, feed_task_status3->valueint);
                    lv_label_set_text(ui_status, text_status);
                    lv_obj_align(ui_status, LV_ALIGN_CENTER, 0, 61);
                }
                cJSON_Delete(root);
            }
            else
            {
                ESP_LOGW(TAG, "Failed to parse JSON");
            }

            free(http_response_buf);
            http_response_buf = NULL;
            http_response_len = 0;
        }
        break;
    case HTTP_EVENT_DISCONNECTED:
        ESP_LOGI(TAG, "HTTP_EVENT_DISCONNECTED");
        break;
    case HTTP_EVENT_REDIRECT:
        ESP_LOGI(TAG, "HTTP_EVENT_REDIRECT");
        break;
    default:
        ESP_LOGW(TAG, "Unhandled HTTP_EVENT ID: %d", evt->event_id);
        break;
    }
    return ESP_OK;
}

static void fetch_device_info()
{
    ESP_LOGI(TAG, "Fetching device info...");

    char url[128];
    snprintf(url, sizeof(url), "%s?UUID=%s", SERVER_URL, DEVICE_UUID);

    esp_http_client_config_t config = {
        .url = url,
        .event_handler = _http_event_handler,
        .method = HTTP_METHOD_GET,
        .timeout_ms = 5000,
        .cert_pem = (const char *)server_thinkfuture_pem_start,
        // .crt_bundle_attach = esp_crt_bundle_attach, // 可选替代方式
    };

    esp_http_client_handle_t client = esp_http_client_init(&config);
    if (!client)
    {
        ESP_LOGE(TAG, "Failed to initialize HTTP client");
        return;
    }

    esp_err_t err = esp_http_client_perform(client);
    if (err != ESP_OK)
    {
        ESP_LOGW(TAG, "HTTP GET failed: %s", esp_err_to_name(err));
        esp_http_client_cleanup(client);
        return;
    }

    int status = esp_http_client_get_status_code(client);
    int content_length = esp_http_client_get_content_length(client);
    ESP_LOGI(TAG, "HTTPS GET Status = %d, Content-Length = %d", status, content_length);

    esp_http_client_cleanup(client); // 别忘了清理
}
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xA7DFED), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 270);
    lv_obj_set_height(ui_Container3, 100);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -65);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Container3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x4A90E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container3, lv_color_hex(0x26CFE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Container3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 270);
    lv_obj_set_height(ui_Container4, 110);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 47);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Container4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x1BA1FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Container4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Container4, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xF2F2F4), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container4, LV_GRAD_DIR_VER, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_timehs = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timehs, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_timehs, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_timehs, -1);
    lv_obj_set_y(ui_timehs, -74);
    lv_obj_set_align(ui_timehs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timehs, "13:30");
    lv_obj_set_style_text_color(ui_timehs, lv_color_hex(0x030A06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timehs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_timehs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timehs, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timehs, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_data = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_data, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_data, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_data, 84);
    lv_obj_set_y(ui_data, -32);
    lv_obj_set_align(ui_data, LV_ALIGN_CENTER);
    lv_label_set_text(ui_data, "2025/2/28");

    ui_status = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_status, -86);
    lv_obj_set_y(ui_status, -30);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "Status:online");
    lv_obj_set_style_text_color(ui_status, lv_color_hex(0x05030A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedplanlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_feedplanlabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_feedplanlabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_feedplanlabel, -80);
    lv_obj_set_y(ui_feedplanlabel, 15);
    lv_obj_set_align(ui_feedplanlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_feedplanlabel, "Feed Plan");
    lv_obj_set_style_text_color(ui_feedplanlabel, lv_color_hex(0x090516), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_feedplanlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feedplanlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedplantext = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_feedplantext, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_feedplantext, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_feedplantext, -120);
    lv_obj_set_y(ui_feedplantext, 61);
    lv_obj_set_align(ui_feedplantext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_feedplantext, "1\n2\n3");

    ui_times = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_times, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_times, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_times, 100);
    lv_obj_set_y(ui_times, -64);
    lv_obj_set_align(ui_times, LV_ALIGN_CENTER);
    lv_label_set_text(ui_times, "");
    lv_obj_set_style_text_color(ui_times, lv_color_hex(0x160F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_times, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加定时器每秒更新一次时钟
    lv_timer_create(update_rtc_time_cb, 1000, NULL);

    // 初始时请求一次服务器数据
    fetch_device_info();

        // 每小时更新一次任务计划
    lv_timer_create((lv_timer_cb_t)fetch_device_info, 5*60*1000, NULL);
}
